# Generated by Django 5.2.17 on 2026-08-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pomodoro", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pomodoro_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasksession",
            name="pomodoro_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_sessions",
                to="pomodoro.pomodorosession",
            ),
        ),
        migrations.AddField(
            model_name="tasksession",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_sessions",
                to="tasks.task",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "target_date"], name="pomodoro_go_user_id_1acd42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "is_completed"], name="pomodoro_go_user_id_339c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pomodorosession",
            index=models.Index(
                fields=["user", "is_completed", "start_time"],
                name="pomodoro_po_user_id_9faec6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pomodorosession",
            index=models.Index(
                fields=["user", "session_type"], name="pomodoro_po_user_id_0d4443_idx"
            ),
        ),
    ]
