# Generated by Django 5.2.17 on 2026-08-29 17:33

import core.mixins.ownership
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=255)),
                ("searched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("definition_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search histories",
                "ordering": ["-searched_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "searched_at"],
                        name="dictionary__user_id_a8c4f0_idx",
                    ),
                    models.Index(
                        fields=["user", "word"], name="dictionary__user_id_5a806c_idx"
                    ),
                ],
            },
            bases=(core.mixins.ownership.OwnedModel, models.Model),
        ),
        migrations.CreateModel(
            name="WordEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(db_index=True, max_length=255)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("note", "Note"), ("bookmark", "Bookmark")],
                        db_index=True,
                        default="note",
                        max_length=10,
                    ),
                ),
                ("custom_note", models.TextField(blank=True, default="")),
                ("definition_data", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Word entries",
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "entry_type"],
                        name="dictionary__user_id_a2e242_idx",
                    ),
                    models.Index(
                        fields=["user", "word", "entry_type"],
                        name="dictionary__user_id_23ecbf_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "word", "entry_type"),
                        name="unique_word_entry_per_user_per_type",
                    )
                ],
            },
            bases=(core.mixins.ownership.OwnedModel, models.Model),
        ),
    ]
