# Generated by Django 5.2.17 on 2026-08-09 04:51

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Email Server", max_length=255),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField()),
                ("username", models.CharField(max_length=255)),
                ("password", fernet_fields.fields.EncryptedTextField()),
                ("use_tls", models.BooleanField(default=False)),
                ("use_ssl", models.BooleanField(default=False)),
                ("default_from_email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Email Server",
                "verbose_name_plural": "Email Servers",
            },
        ),
        migrations.CreateModel(
            name="PhoneServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Phone Server", max_length=255),
                ),
                ("account_sid", models.CharField(max_length=255)),
                ("auth_token", fernet_fields.fields.EncryptedTextField()),
                ("from_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Phone Server",
                "verbose_name_plural": "Phone Servers",
            },
        ),
    ]
