# Generated by Django 5.2.17 on 2026-09-12 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_streak', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('badge_icon', models.CharField(blank=True, max_length=100)),
                ('badge_color', models.CharField(default='gold', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['required_streak'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('leaderboard_type', models.CharField(choices=[('global', 'Global Leaderboard'), ('weekly', 'Weekly Leaderboard'), ('monthly', 'Monthly Leaderboard'), ('all_time', 'All-Time Leaderboard')], db_index=True, max_length=20)),
                ('top_entries', models.JSONField(default=list)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('average_streak', models.FloatField(default=0.0)),
                ('median_streak', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date', 'leaderboard_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField(db_index=True, help_text="Date of activity in user's timezone")),
                ('pomodoro_count', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('goals_achieved', models.PositiveIntegerField(default=0)),
                ('total_study_minutes', models.PositiveIntegerField(default=0)),
                ('activity_types', models.JSONField(default=list, help_text='List of activity types logged for this day')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['user', 'activity_date'], name='leaderboard_user_id_6ca205_idx'), models.Index(fields=['activity_date'], name='leaderboard_activit_9c2ac2_idx')],
                'unique_together': {('user', 'activity_date')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leaderboard_type', models.CharField(choices=[('global', 'Global Leaderboard'), ('weekly', 'Weekly Leaderboard'), ('monthly', 'Monthly Leaderboard'), ('all_time', 'All-Time Leaderboard')], db_index=True, max_length=20)),
                ('rank', models.PositiveIntegerField(help_text='Current rank in the leaderboard', validators=[django.core.validators.MinValueValidator(1)])),
                ('streak_score', models.PositiveIntegerField(default=0)),
                ('activity_score', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['leaderboard_type', 'rank'],
                'indexes': [models.Index(fields=['leaderboard_type', 'rank'], name='leaderboard_leaderb_74fa7b_idx'), models.Index(fields=['leaderboard_type', 'total_score'], name='leaderboard_leaderb_6071c2_idx')],
                'unique_together': {('user', 'leaderboard_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='StreakFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_for_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_for_date'],
                'indexes': [models.Index(fields=['user', 'used_for_date'], name='leaderboard_user_id_7a342d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('streak_at_achievement', models.PositiveIntegerField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievers', to='leaderboard.streakmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days of activity', validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='All-time longest streak', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_activity_date', models.DateField(blank=True, db_index=True, help_text="Date of last activity in user's timezone", null=True)),
                ('last_activity_timestamp', models.DateTimeField(blank=True, help_text='Precise timestamp of last activity for debugging', null=True)),
                ('streak_start_date', models.DateField(blank=True, help_text='Date when current streak began', null=True)),
                ('user_timezone', models.CharField(default='UTC', help_text="User's timezone for streak calculation (e.g., 'America/New_York')", max_length=50)),
                ('is_frozen', models.BooleanField(default=False, help_text="If True, streak won't be broken due to inactivity")),
                ('frozen_until', models.DateField(blank=True, help_text='Date until which streak is frozen', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak', '-longest_streak'],
                'indexes': [models.Index(fields=['current_streak'], name='leaderboard_current_bc582c_idx'), models.Index(fields=['longest_streak'], name='leaderboard_longest_bfb54a_idx'), models.Index(fields=['last_activity_date'], name='leaderboard_last_ac_d5f9ec_idx'), models.Index(fields=['user', 'last_activity_date'], name='leaderboard_user_id_9c3e28_idx')],
            },
        ),
    ]
