# Generated by Django 5.2.17 on 2026-08-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="accepted_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_friendship",
                to="social.friendrequest",
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user_high",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_as_high",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user_low",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_as_low",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpresencestate",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presence_state",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="friendrequest",
            index=models.Index(
                fields=["receiver", "status", "created_at"],
                name="social_frie_receive_2285ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="friendrequest",
            index=models.Index(
                fields=["sender", "status", "created_at"],
                name="social_frie_sender__a2f4c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                fields=("sender", "receiver"), name="uniq_friend_request_direction"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["user_low", "user_high"], name="social_frie_user_lo_042c90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["created_at"], name="social_frie_created_0416d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("user_low", "user_high"), name="uniq_friendship_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_low__lt", models.F("user_high"))),
                name="friendship_users_are_ordered",
            ),
        ),
        migrations.AddIndex(
            model_name="userpresencestate",
            index=models.Index(
                fields=["is_online", "last_seen"], name="social_user_is_onli_721c00_idx"
            ),
        ),
    ]
